name: yday
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # For UI
  platform_date_picker: ^0.0.4+1
  menu_button: ^1.3.1
  multi_select_flutter: ^4.0.0
  time_picker_widget: ^1.0.0+9
  datetime_picker_formfield: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  confetti: ^0.5.5

  provider: ^5.0.0
  intl: ^0.17.0
  image_picker: ^0.7.3
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  url_launcher: ^6.0.3
  table_calendar: ^2.3.3
  popover: ^0.2.1
  hawk_fab_menu: ^0.3.2
  adaptive_dialog: ^0.10.0+5
  http: ^0.13.1
  firebase_storage: ^8.0.1
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_database: ^6.1.2
  google_sign_in: ^5.0.1
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  path: ^1.8.0
  share: ^2.0.2
  image_downloader: ^0.30.0
  flutter_cache_manager: ^3.0.1
  flutter_vesti_share: ^0.0.5
  font_awesome_flutter: ^9.0.0
  multi_image_picker: ^4.8.0
  flutter_secure_storage: ^4.1.0
  enhanced_drop_down: ^0.1.6
  flutter_absolute_path: ^1.0.6
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0
  scaled_list: ^1.0.1+6
  bottom_navy_bar: ^6.0.0
  custom_navigation_bar: ^0.8.1
  text_editor: ^0.4.0+1
  permission_handler: ^8.1.1
  flat_icons_flutter: ^1.0.2
#  fluttercontactpicker: ^4.0.0
#  contact_picker_v: ^0.0.1
#  flutter_native_contact_picker: ^0.0.6
  native_contact_picker: ^0.0.6
  flutter_animation_progress_bar: ^2.0.0
  bottom_bar_page_transition: ^2.0.0
  titled_navigation_bar: ^4.1.0
#  zoom_pinch_overlay: ^1.1.2
  pinch_zoom: ^0.1.0
  account_picker: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Libre Baskerville
      fonts:
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Regular.ttf
    - family: Kaushan Script
      fonts:
          - asset: assets/fonts/Kaushan_Script/KaushanScript-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
